#!/bin/bash
PWD=`pwd`
mv $PWD/ec2sshpanes /usr/local/bin/sshall
mv $PWD/terminator-split /usr/local/bin/terminator-split
chmod +x /usr/local/bin/sshall
chmod +x /usr/local/bin/terminator-split
rm -rf $PWD/terminator-split
